name: loader_sample
version: 1.0.1
dependencies:
 polymerize: ^0.9.3
 polymer_element: ^2.0.4
 html5 : ^0.1.4
 polymer_elements:
  git:
    url: https://github.com/polymer-dart/polymerize_elements.git
    ref: v0.4.1

transformers:
 - polymerize:
    entry-point: web/*.dart
#dependency_overrides:
#   polymer_element:
#     path: ../polymer_element
#  polymerize:
#    path: ../polymerize
#  polymerize_common:
#    path: ../polymerize_common
web:
 compiler:
   debug: dartdevc
   release: dartdevc
